(add-to-list 'load-path "~/.emacs.d/init/auto-complete")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/init/auto-complete/ac-dict")
(ac-config-default)
(provide 'init-auto-complete)
